server:
  port: ${PORT:8889}

spring:
  application:
    name: config-service

  cloud:
    config:
      label: master
      server:
        native: # In native profile by default it will provide config files from the resources/config/ folder, override that
          search-locations: file:./config-services-properties

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: error
    org.springframework: info
    com.melardev: debug

